### ISSUE TITLE
Incompatibility with `eslint-plugin-deprecation`

### ISSUE THREAD

**Issue by marekdedic** [ota-meshi/eslint-plugin-svelte#278]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

8.26.0

### What version of `eslint-plugin-svelte` are you using?

2.11.0

### What did you do?

<details>
<summary>Configuration</summary>

```json
{
  "parser": "svelte-eslint-parser",
  "parserOptions": {
    "extraFileExtensions": [".svelte"]
  },
  "plugins": ["deprecation"],
  "rules": {
    "deprecation/deprecation": "warn"
  }
}
```
</details>

```svelte
<div {progress} />
```

### What did you expect to happen?

Eslint runs without errors

### What actually happened?

```
Oops! Something went wrong! :(

ESLint: 8.26.0

TypeError: Cannot read properties of undefined (reading 'parent')
Occurred while linting /home/user/project/App.svelte:5
Rule: "deprecation/deprecation"
    at getSymbol (/home/user/project/node_modules/eslint-plugin-deprecation/dist/rules/deprecation.js:184:25)
    at getDeprecation (/home/user/project/node_modules/eslint-plugin-deprecation/dist/rules/deprecation.js:172:20)
    at identifierRule (/home/user/project/node_modules/eslint-plugin-deprecation/dist/rules/deprecation.js:63:29)
    at ruleErrorHandler (/home/user/project/node_modules/eslint/lib/linter/linter.js:1115:28)
    at /home/user/project/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/user/project/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/user/project/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/home/user/project/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/home/user/project/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
```

### Link to Minimal Reproducible Example

https://gist.github.com/marekdedic/b5870cec58295f484b699fa6f60e96c7

**Comment by marekdedic** [comment]
Hi,
thanks, I can confirm this works for me :)
